name: Deploy to Tencent Cloud

on:
  push:
    branches: [ main ]  # 当 main 分支有推送时触发

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      # 设置 Node.js 环境
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      # 构建 Docker 镜像
      - name: Build Docker image
        run: |
          docker build -t next-boilerplate:latest .
          docker save next-boilerplate:latest > image.tar
          
      # 部署到腾讯云
      - name: Deploy to Tencent Cloud
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.TENCENT_HOST }}
          key: ${{ secrets.TENCENT_PRIVATE_KEY }}
          source: "image.tar,docker-compose.yml"
          target: "/opt/next-boilerplate"
          
      # 在服务器上运行部署脚本
      - name: Execute deploy script
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.TENCENT_HOST }}
          key: ${{ secrets.TENCENT_PRIVATE_KEY }}
          script: |
            cd /opt/next-boilerplate
            docker load < image.tar
            docker-compose down
            docker-compose up -d